# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QComboBox, QDateEdit,
    QDateTimeEdit, QDoubleSpinBox, QGroupBox, QHeaderView,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QSlider, QSpinBox, QTableWidget, QTableWidgetItem,
    QTextEdit, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.setEnabled(True)
        Widget.resize(1000, 800)
        self.intraocularPressureSlider = QSlider(Widget)
        self.intraocularPressureSlider.setObjectName(u"intraocularPressureSlider")
        self.intraocularPressureSlider.setGeometry(QRect(560, 470, 221, 41))
        self.intraocularPressureSlider.setMinimum(10)
        self.intraocularPressureSlider.setMaximum(50)
        self.intraocularPressureSlider.setValue(20)
        self.intraocularPressureSlider.setOrientation(Qt.Orientation.Horizontal)
        self.loadButton = QPushButton(Widget)
        self.loadButton.setObjectName(u"loadButton")
        self.loadButton.setGeometry(QRect(530, 120, 111, 41))
        self.saveButton = QPushButton(Widget)
        self.saveButton.setObjectName(u"saveButton")
        self.saveButton.setGeometry(QRect(530, 170, 111, 41))
        self.resetButton = QPushButton(Widget)
        self.resetButton.setObjectName(u"resetButton")
        self.resetButton.setGeometry(QRect(660, 170, 111, 41))
        self.simulateButton = QPushButton(Widget)
        self.simulateButton.setObjectName(u"simulateButton")
        self.simulateButton.setGeometry(QRect(660, 120, 111, 41))
        self.processedLabel = QLabel(Widget)
        self.processedLabel.setObjectName(u"processedLabel")
        self.processedLabel.setGeometry(QRect(320, 250, 281, 161))
        self.originalLabel = QLabel(Widget)
        self.originalLabel.setObjectName(u"originalLabel")
        self.originalLabel.setGeometry(QRect(40, 250, 271, 161))
        self.dateTimeEdit = QDateTimeEdit(Widget)
        self.dateTimeEdit.setObjectName(u"dateTimeEdit")
        self.dateTimeEdit.setGeometry(QRect(90, 10, 194, 26))
        self.tableTimeline = QTableWidget(Widget)
        if (self.tableTimeline.columnCount() < 4):
            self.tableTimeline.setColumnCount(4)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableTimeline.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableTimeline.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableTimeline.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableTimeline.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        self.tableTimeline.setObjectName(u"tableTimeline")
        self.tableTimeline.setGeometry(QRect(30, 450, 511, 121))
        self.tableTimeline.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.labelRiskLevel = QLabel(Widget)
        self.labelRiskLevel.setObjectName(u"labelRiskLevel")
        self.labelRiskLevel.setGeometry(QRect(560, 530, 63, 20))
        self.groupBox = QGroupBox(Widget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QRect(40, 60, 451, 181))
        self.groupBox.setCheckable(False)
        self.textEditNotes = QTextEdit(self.groupBox)
        self.textEditNotes.setObjectName(u"textEditNotes")
        self.textEditNotes.setGeometry(QRect(260, 84, 171, 51))
        self.lineEditSurname = QLineEdit(self.groupBox)
        self.lineEditSurname.setObjectName(u"lineEditSurname")
        self.lineEditSurname.setGeometry(QRect(110, 70, 113, 26))
        self.lineEditName = QLineEdit(self.groupBox)
        self.lineEditName.setObjectName(u"lineEditName")
        self.lineEditName.setGeometry(QRect(110, 30, 113, 26))
        self.lineEditID = QLineEdit(self.groupBox)
        self.lineEditID.setObjectName(u"lineEditID")
        self.lineEditID.setGeometry(QRect(110, 110, 113, 26))
        self.dateEditBirth = QDateEdit(self.groupBox)
        self.dateEditBirth.setObjectName(u"dateEditBirth")
        self.dateEditBirth.setGeometry(QRect(320, 30, 110, 26))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 30, 63, 20))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 70, 63, 20))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 110, 63, 20))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(260, 60, 63, 20))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(260, 30, 63, 20))
        self.comboBoxGender = QComboBox(self.groupBox)
        self.comboBoxGender.addItem("")
        self.comboBoxGender.addItem("")
        self.comboBoxGender.addItem("")
        self.comboBoxGender.setObjectName(u"comboBoxGender")
        self.comboBoxGender.setGeometry(QRect(110, 150, 76, 26))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 150, 63, 20))
        self.showGraphButton = QPushButton(Widget)
        self.showGraphButton.setObjectName(u"showGraphButton")
        self.showGraphButton.setGeometry(QRect(660, 290, 111, 41))
        self.savePatientButton = QPushButton(Widget)
        self.savePatientButton.setObjectName(u"savePatientButton")
        self.savePatientButton.setGeometry(QRect(550, 70, 93, 29))
        self.loadPatientButton = QPushButton(Widget)
        self.loadPatientButton.setObjectName(u"loadPatientButton")
        self.loadPatientButton.setGeometry(QRect(660, 70, 93, 29))
        self.spinBoxCSF = QSpinBox(Widget)
        self.spinBoxCSF.setObjectName(u"spinBoxCSF")
        self.spinBoxCSF.setGeometry(QRect(180, 690, 42, 26))
        self.opticNerveLabel = QLabel(Widget)
        self.opticNerveLabel.setObjectName(u"opticNerveLabel")
        self.opticNerveLabel.setGeometry(QRect(160, 600, 161, 20))
        self.btnShowTPD = QPushButton(Widget)
        self.btnShowTPD.setObjectName(u"btnShowTPD")
        self.btnShowTPD.setGeometry(QRect(160, 650, 121, 29))
        self.exportButton = QPushButton(Widget)
        self.exportButton.setObjectName(u"exportButton")
        self.exportButton.setGeometry(QRect(390, 600, 93, 29))
        self.importButton = QPushButton(Widget)
        self.importButton.setObjectName(u"importButton")
        self.importButton.setGeometry(QRect(390, 660, 93, 29))
        self.doubleSpinBox = QDoubleSpinBox(Widget)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(820, 40, 62, 26))
        self.labelTPD = QLabel(Widget)
        self.labelTPD.setObjectName(u"labelTPD")
        self.labelTPD.setGeometry(QRect(170, 730, 63, 20))

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.loadButton.setText(QCoreApplication.translate("Widget", u"Select Image", None))
        self.saveButton.setText(QCoreApplication.translate("Widget", u"Save", None))
        self.resetButton.setText(QCoreApplication.translate("Widget", u"Reset", None))
        self.simulateButton.setText(QCoreApplication.translate("Widget", u"Simulate", None))
        self.processedLabel.setText(QCoreApplication.translate("Widget", u"Processed Image", None))
        self.originalLabel.setText(QCoreApplication.translate("Widget", u"Original Image", None))
        ___qtablewidgetitem = self.tableTimeline.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Widget", u"Date:", None));
        ___qtablewidgetitem1 = self.tableTimeline.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Widget", u"New Column", None));
        ___qtablewidgetitem2 = self.tableTimeline.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Widget", u"IOP(mmHg):", None));
        ___qtablewidgetitem3 = self.tableTimeline.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Widget", u"Note:", None));
        self.labelRiskLevel.setText(QCoreApplication.translate("Widget", u"Risk Level", None))
        self.groupBox.setTitle(QCoreApplication.translate("Widget", u"Patient Information", None))
        self.label.setText(QCoreApplication.translate("Widget", u"Name:", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"Surname:", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"ID:", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"Note:", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"Birth:", None))
        self.comboBoxGender.setItemText(0, QCoreApplication.translate("Widget", u"Woman", None))
        self.comboBoxGender.setItemText(1, QCoreApplication.translate("Widget", u"Man", None))
        self.comboBoxGender.setItemText(2, QCoreApplication.translate("Widget", u"Unknown", None))

        self.label_6.setText(QCoreApplication.translate("Widget", u"Gender:", None))
        self.showGraphButton.setText(QCoreApplication.translate("Widget", u"Show Graph", None))
        self.savePatientButton.setText(QCoreApplication.translate("Widget", u"Save Patient", None))
        self.loadPatientButton.setText(QCoreApplication.translate("Widget", u"Load Patient", None))
        self.opticNerveLabel.setText(QCoreApplication.translate("Widget", u"Optic Nerve Simulation", None))
        self.btnShowTPD.setText(QCoreApplication.translate("Widget", u"Show TPD Graph:", None))
        self.exportButton.setText(QCoreApplication.translate("Widget", u"Save All Data", None))
        self.importButton.setText(QCoreApplication.translate("Widget", u"Load Data", None))
        self.labelTPD.setText(QCoreApplication.translate("Widget", u"TPD", None))
    # retranslateUi

